param(
    [string]$DashboardPath = (Join-Path $PSScriptRoot "..\src\launcher\dashboard.html"),
    [string]$LauncherPath = (Join-Path $PSScriptRoot "..\src\SmartBackgroundNap.cs"),
    [string]$ManifestPath = (Join-Path $PSScriptRoot "..\src\app.manifest")
)

$ErrorActionPreference = "Stop"
$dashboard = Get-Content -LiteralPath (Resolve-Path -LiteralPath $DashboardPath) -Raw
$launcher = Get-Content -LiteralPath (Resolve-Path -LiteralPath $LauncherPath) -Raw
$manifest = Get-Content -LiteralPath (Resolve-Path -LiteralPath $ManifestPath) -Raw

function Assert-Contains {
    param([string]$Source, [string]$Needle, [string]$Message)
    if (-not $Source.Contains($Needle)) { throw $Message }
}

function Assert-NotContains {
    param([string]$Source, [string]$Needle, [string]$Message)
    if ($Source.Contains($Needle)) { throw $Message }
}

function Assert-Matches {
    param([string]$Source, [string]$Pattern, [string]$Message)
    if ($Source -notmatch $Pattern) { throw $Message }
}

Assert-Contains $dashboard "v0.7.0 responsive architecture" "Responsive architecture layer is missing."
Assert-Contains $dashboard "height:100dvh" "Root layout must use dynamic viewport height."
Assert-Contains $dashboard "overflow-x:clip" "Workspace must clip accidental root overflow after fixing source layouts."
Assert-Contains $dashboard "grid-template-columns:repeat(auto-fit,minmax(min(100%,220px),1fr))" "Dashboard cards must use adaptive columns."
Assert-Contains $dashboard 'body.view-games .gamesGrid[data-view="grid"]{grid-template-columns:repeat(4,minmax(0,1fr))' "Games grid must keep stable columns so one filtered result does not stretch."
Assert-Contains $dashboard 'body.view-games .gamesGrid[data-view="grid"] .gamePoster{aspect-ratio:3/4' "Games grid covers must keep a bounded card proportion."
Assert-Contains $dashboard 'body.view-games .gamesGrid[data-view="list"] .gameBody{display:grid!important;grid-template-columns:minmax(0,1fr) minmax(178px,220px)' "Games list view must reserve a compact action column."
Assert-Contains $dashboard 'body.view-games .gameCardControls .gameMiniBtn.primary{flex:0 0 auto' "Games list primary actions must not stretch into full-width bars."
Assert-Contains $dashboard "onlyFocusedResult" "Games continue banner must avoid duplicating the only focused pending card."
Assert-Contains $dashboard "max-height:calc(100dvh - 24px)" "Modals must respect dynamic viewport height."
Assert-Contains $dashboard "body.modal-open .workspace" "Background scroll lock for modals is missing."
Assert-Contains $dashboard "MODAL_IDS" "Central modal registry is missing."
Assert-Contains $dashboard "function openOverlay" "Central modal open helper is missing."
Assert-Contains $dashboard "function closeOverlay" "Central modal close helper is missing."
Assert-Contains $dashboard 'ev.key==="Escape"' "Modals must close with Escape."
Assert-Contains $dashboard ".manager .thead{display:none!important}" "Live manager must switch away from a fixed technical table in narrow layouts."
Assert-Contains $dashboard ".manager .row{width:100%!important;min-width:0!important;max-width:100%!important;display:grid!important" "Live manager row card layout is missing."
Assert-Contains $dashboard ".gameCard{display:grid!important;grid-template-columns:minmax(92px,128px) minmax(0,1fr)!important" "Compact game-card list layout is missing."
Assert-Contains $dashboard ".nav:after{display:none!important}" "Compact rail tooltips must not overflow narrow windows."
Assert-Contains $dashboard "v0.7.0 gap repair" "Dashboard hero gap repair is missing."
Assert-Contains $dashboard ".commandHero .chipRow{margin-top:0!important}" "Dashboard chip row must not be pushed by auto margins."
Assert-Contains $dashboard "v0.7.0 timeline readability repair" "Timeline readability repair is missing."
Assert-Contains $dashboard ".timeline .eventLine,.eventLine.eventCard" "Timeline event cards must be governed by the final responsive repair."
Assert-Contains $dashboard "v0.7.0 games header stability" "Games header stability layer is missing."
Assert-Contains $dashboard "body.view-games .wordmarkLogo" "Games view must stabilize the launcher logo."
Assert-Contains $dashboard 'document.body.classList.toggle("view-games"' "View state class for Games is missing."
Assert-Contains $dashboard "chromeCompactActive ? y>18 : y>66" "Chrome compact scroll hysteresis is missing."
Assert-Contains $dashboard "v0.7.0 hard layout cleanup" "Hard layout cleanup layer is missing."
Assert-Contains $dashboard "body.view-dashboard .command.panel" "Dashboard command container must not show false empty surface."
Assert-Contains $dashboard "display:flex!important;" "Timeline must use flex column stacking."
Assert-Contains $dashboard "flex-direction:column!important" "Timeline must use flex column stacking."
Assert-Contains $dashboard "height:auto!important" "Game preset modal must not keep fixed viewport height."
Assert-Contains $dashboard "v0.7.0 structural rhythm repair" "Structural rhythm repair layer is missing."
Assert-Contains $dashboard 'document.body.appendChild(el)' "Modals must be portaled to the body instead of remaining inside page scroll contexts."
Assert-Contains $dashboard '<div class="eventHead">' "Timeline events must render a real header row instead of absolute/fragile inline layout."
Assert-Contains $dashboard ".eventHead{" "Timeline event header CSS is missing."
Assert-Contains $dashboard ".engineCard .actions #restoreBtn" "Engine restore action must be explicitly balanced in the action grid."
Assert-Contains $dashboard "grid-column:1 / -1!important" "Engine restore action must span the action grid when two columns are used."
Assert-Contains $dashboard "#gamePresetOverlay.open" "Game preset overlay must have a viewport-fixed open state."
Assert-Contains $dashboard "#gamePresetOverlay .gamePresetClose" "Game preset close button must be governed by modal header rules."
Assert-Contains $dashboard '#gamePresetOverlay .gameActions' "Game preset footer action grid is missing."
Assert-Contains $dashboard 'grid-template-areas:"restore cancel primary"' "Game preset action grid must avoid abandoned empty cells."
Assert-Contains $dashboard '#gamePresetOverlay .gameOptions{' "Game preset optimization groups must have independent column layout."
Assert-Contains $dashboard 'align-items:start!important' "Independent modal/action groups must align to their natural content height."
Assert-Contains $dashboard '@media(min-width:901px)' "Wide game preset modal must use a distinct two-column rhythm rule."
Assert-Contains $dashboard "v0.7.2 game preset modal final polish" "Game preset modal final polish layer is missing."
Assert-Contains $dashboard "v0.7.2 game preset modal viewport scroll repair" "Game preset modal must lock its outer height and route technical details into internal scrollers."
Assert-Contains $dashboard "v0.7.3 game preset modal responsive refinement" "Game preset modal responsive refinement layer is missing."
Assert-Contains $dashboard "v0.7.3 game preset portrait polish" "Game preset modal portrait polish layer is missing."
Assert-Contains $dashboard "#gamePresetOverlay .gamePresetPanel{display:grid!important;width:min(1000px,calc(100vw - 32px))!important;height:min(900px,calc(100dvh - 32px))" "Game preset modal must use a bounded viewport height instead of growing with technical details."
Assert-Contains $dashboard "#gamePresetOverlay .gamePresetShell{display:grid!important;grid-template-columns:minmax(248px,300px) minmax(0,1fr)!important;height:100%" "Game preset shell must fill the bounded modal so only internal areas scroll."
Assert-Contains $dashboard "#gamePresetOverlay .gamePresetLead{scrollbar-gutter:stable" "Game preset sidebar must keep its scrollbar away from the column divider."
Assert-Contains $dashboard "#gamePresetOverlay .gamePresetMeta{margin-top:0!important" "Game preset sidebar metadata must follow natural flow instead of being pushed offscreen."
Assert-Contains $dashboard "#gamePresetOverlay .gamePresetReview{min-height:0!important;overflow:auto" "Game preset central review area must scroll independently when recipes grow."
Assert-Contains $dashboard "#gamePresetOverlay .gamePresetFooter{display:grid" "Game preset decision footer must be separated from the scrollable review list."
Assert-Contains $dashboard "#gamePresetOverlay .gamePresetFootSummary{position:static" "Game preset summary row must stay in the fixed footer region, not inside the scrolling list."
Assert-Contains $dashboard "#gamePresetOverlay .gamePresetTechnical{width:auto!important;max-width:max-content!important;flex:0 0 auto" "Game preset technical details toggle must stay compact in vertical layouts."
Assert-Contains $dashboard "@media(max-width:900px),(max-aspect-ratio:4/5)" "Game preset modal must switch to a compact one-column layout for vertical/narrow screens."
Assert-Contains $dashboard "#gamePresetOverlay .gamePresetCompactInfo:not([open]) .gamePresetMeta{display:none" "Game preset narrow sidebar details must be collapsible instead of squeezing the modal."
Assert-Contains $dashboard "gamePresetCompactPreview" "Game preset narrow sidebar disclosure must expose a real compact preview line."
Assert-Contains $dashboard "#gamePresetOverlay .gamePresetReview{align-content:start!important;align-items:start!important;grid-auto-rows:max-content" "Game preset compact cards must use natural row height instead of stretched viewport rows."
Assert-Contains $dashboard "#gamePresetOverlay .gameOptionCard{align-self:start!important;min-height:0!important;height:auto" "Game preset option cards must avoid inherited fixed/min heights in portrait layouts."
Assert-Contains $dashboard '#gamePresetOverlay .gamePresetPanel[data-applied-clean="true"] .gameActions .btn.primary{display:none' "Applied clean preset state must not leave a giant disabled primary CTA in compact layouts."
Assert-Contains $dashboard ".gamePresetTechnical input{position:absolute!important;opacity:0!important" "Game preset technical details control must be a Design System toggle, not a native checkbox."
Assert-Contains $dashboard ".gameActions .gameRestoreBtnNeutral" "Game preset restore button must be neutral, not destructive by default."
Assert-Contains $dashboard "v0.7.0 dashboard safe recovery and compositor performance" "Dashboard safe space/performance recovery layer is missing."
Assert-NotContains $dashboard "display:contents!important" "Dashboard must not use display:contents for structural panels; it can squeeze content into false columns."
Assert-NotContains $dashboard "commandPrimary" "Dashboard must not depend on the removed commandPrimary wrapper."
Assert-Contains $dashboard "v0.7.0 dashboard rescue" "Dashboard rescue layer is missing."
Assert-Contains $dashboard "no squeezed columns" "Dashboard rescue must document the squeezed-column regression."
Assert-Contains $dashboard "grid-template-columns:1fr!important" "Dashboard medium-width command panel must fall back to one full-width column."
Assert-Contains $dashboard "body.view-dashboard .commandMainFlow" "Dashboard main flow wrapper is missing."
Assert-Contains $dashboard "body.view-dashboard .commandMainFlow>.cards" "Dashboard quick cards must stay in the main overview flow."
Assert-Contains $dashboard "v0.7.4 dashboard de-duplication" "Dashboard de-duplication layer is missing."
Assert-Contains $dashboard "formatInterventionInsight" "Dashboard quick action card must show a unique intervention insight, not the raw applied-action string."
Assert-Contains $dashboard "formatUdpLastDetection" "Dashboard quick UDP card must show last detection, not duplicate Zero Ping state."
Assert-Contains $dashboard "formatShaderCacheInsight" "Dashboard quick ShaderBoost card must show cache health, not duplicate telemetry."
Assert-Contains $dashboard "liveEl.hidden=!(syncIssue||coreIssue)" "Panel synced pill must stay hidden while sync is healthy and only surface sync or service issues."
Assert-Contains $dashboard "v0.7.6 realtime control panel polish" "Realtime control polish layer is missing."
Assert-Contains $dashboard 'id="engineSessionMain"' "Realtime control must expose protected-apps session headline."
Assert-Contains $dashboard 'class="engineProcessBlock"' "Realtime control processing block is missing."
Assert-Contains $dashboard 'class="meter engineRhythm"' "Realtime control pulse block is missing."
Assert-Contains $dashboard 'id="engineRingCaption"' "Realtime control ring caption is missing."
Assert-Contains $dashboard 'id="engineRingDetail"' "Realtime control ring detail is missing."
Assert-Contains $dashboard 'id="engineCycleLine"' "Realtime control cycle line is missing."
Assert-Contains $dashboard 'id="enginePulseCard"' "Realtime control last-pass card must be addressable."
Assert-Contains $dashboard 'id="enginePulseDetails"' "Realtime control last-pass details container is missing."
Assert-Contains $dashboard "function engineProtectionRingDegrees" "Realtime control ring must be based on real session proportions."
Assert-Contains $dashboard "function formatControlDetail" "Realtime control header detail must remove duplicate app counts."
Assert-Contains $dashboard "function formatEngineRingCaption" "Realtime control ring caption must show grouped-app context, not duplicate protected-app headline."
Assert-Contains $dashboard "function formatCycleState" "Realtime control metric grid must show cycle state instead of duplicating the next-cycle timer."
Assert-Contains $dashboard "function formatWakeProtectionState" "Realtime control return protection must use a clear operational state."
Assert-Contains $dashboard "function engineActionMetric" "Realtime control applied actions must use structured mini-metrics."
Assert-Contains $dashboard "engineActionGrid" "Realtime control applied actions must render as a compact 2x2 grid."
Assert-Contains $dashboard "Sem alívio de memória nesta sessão" "Realtime control zero-memory detail must use reassuring copy instead of raw 0 MB."
Assert-Contains $dashboard "processos monitorados" "Realtime control ring caption must use process context instead of repeating apps agrupados."
Assert-Contains $dashboard "realtime micro polish finish" "Realtime control final micro-polish layer is missing."
Assert-Contains $dashboard "#control .actions #apply:after{content:none" "Realtime control primary button must not show a decorative dot at rest."
Assert-Contains $dashboard "#control .actions #apply.motion-pending:after" "Realtime control primary button must preserve the real loading spinner."
Assert-Contains $dashboard "if(raw==="Work") return t("modeWork")" "Realtime control context must translate Work in the main UI."
Assert-Contains $dashboard "@property --ring-deg" "Realtime control ring should transition real ring-degree updates."
Assert-Contains $dashboard "function formatEnginePulseDetails" "Realtime control last-pass detail renderer is missing."
Assert-Contains $dashboard "function installControlPulseToggle" "Realtime control last-pass expansion binding is missing."
Assert-Contains $dashboard "installControlPulseToggle()" "Realtime control last-pass toggle must be installed on DOMContentLoaded."
Assert-Contains $dashboard "#control .engineSummary span:before,#control .engineSummary span:after" "Realtime control must suppress old boxed metric decoration."
Assert-Contains $dashboard "#control.engineCard.is-working .engineCycleLine i b" "Realtime control cycle activity must only animate while working."
Assert-Contains $dashboard "function updateControlActions" "Realtime control must centralize pass, cancel and motor-pause button states."
Assert-Contains $dashboard "cancelPass" "Realtime control must label cancellable runs as Cancelar passe, not Parar."
Assert-Contains $dashboard "function formatSessionDuration" "Realtime control session time must be formatted as duration, not a clock timestamp."
Assert-Contains $dashboard "function formatLastPassStamp" "Realtime control last-pass timestamp must be distinct from session duration."
Assert-Contains $dashboard "Análise em andamento" "Realtime control must show analysis-in-progress copy during a running pass."
Assert-Contains $dashboard "realtime state clarity" "Realtime control pass-state clarity CSS layer is missing."
Assert-Contains $dashboard "v0.7.6 realtime rework" "Realtime final regression fix layer is missing."
Assert-Contains $dashboard "v0.7.10 dashboard independent regions" "Dashboard independent primary/activity region layer is missing."
Assert-Contains $dashboard 'class="primaryRegion"' "Dashboard must expose an independent primary region."
Assert-Contains $dashboard 'class="primaryTopGrid"' "Dashboard primary region must contain its own top grid."
Assert-Contains $dashboard 'class="activityRail"' "Dashboard activity panel must live in an independent activity rail."
Assert-Contains $dashboard "body.view-dashboard .primaryTopGrid>#control.engineCard" "Realtime control must live beside the overview inside the primary top grid."
Assert-Contains $dashboard "body.view-dashboard .activityRail>.activityPanel" "Activity panel must live in the independent activity rail."
Assert-Contains $dashboard "body.view-dashboard .primaryRegion>#modeDeck" "Engine mode must follow the primary region flow instead of a global dashboard row."
Assert-Contains $dashboard "--activity-rail-target-height" "Activity rail must expose a measured height so the log can reach the PC profile start."
Assert-Contains $dashboard "function syncActivityRailHeight" "Activity rail height sync function is missing."
Assert-Contains $dashboard "installActivityRailHeightSync()" "Activity rail height sync must be installed on DOMContentLoaded."
Assert-NotContains $dashboard "body.view-dashboard .rightCol>#control.engineCard" "Realtime control must not be validated against the retired rightCol layout."
Assert-Contains $dashboard "grid-template-columns:repeat(2,minmax(52px,1fr))" "Applied action metrics must use a compact 2x2 grid."
Assert-Contains $dashboard "formatLastPassStamp(s,canExpand)" "Last-pass compact stamp must not duplicate the last-intervention relative counter."
Assert-Contains $dashboard "#control .engineSummary span:nth-child(-n+2)" "Realtime control processing first row must use compact natural-height cells."
Assert-Contains $dashboard "pass-cancel" "Realtime control must style a dedicated cancel-pass action instead of showing Parar."
Assert-NotContains $dashboard 'stop:"Parar"' "Realtime control Portuguese copy must not expose ambiguous Parar."
Assert-NotContains $dashboard 's.CanStop?t("stop"):t("apply")' "Realtime control primary button must not switch directly from Optimize to Stop."
Assert-Contains $dashboard "v0.7.5 activity hierarchy" "Activity panel hierarchy layer is missing."
Assert-Contains $dashboard 'class="activityGroupLabel activityImpactLabel"' "Activity panel must label current impact."
Assert-Contains $dashboard 'class="activityGroupLabel activityResultsLabel"' "Activity panel must label session results."
Assert-Contains $dashboard 'class="activityGroupLabel activityResourcesLabel"' "Activity panel must label active resources."
Assert-Contains $dashboard 'class="activityGroupLabel activityRecentLabel"' "Activity panel must label recent activity."
Assert-Contains $dashboard 'class="activityInsightButton"' "Activity panel insights control must be a real button."
Assert-Contains $dashboard "function scrollActivityEvents" "Activity insights button must perform a real action."
Assert-Contains $dashboard "formatMemoryReliefDetail" "Activity panel must use a complementary memory-relief formatter."
Assert-Contains $dashboard 'id="reclaimedInline"' "Activity panel must attach latest relief to reclaimed memory instead of using an orphan card."
Assert-Contains $dashboard "hasMemoryReliefDetail(actions)" "Activity panel must hide inline memory-relief detail when it has no unique data."
Assert-Contains $dashboard 'data-activity-card="memory"' "Activity panel memory card must expose accordion metadata."
Assert-Contains $dashboard "function setActivityDetails" "Activity panel accordion detail renderer is missing."
Assert-Contains $dashboard "function installActivityAccordion" "Activity panel accordion event binding is missing."
Assert-Contains $dashboard "function formatTopImpact" "Activity panel top-impact fallback is missing."
Assert-Contains $dashboard "activityChevron" "Activity panel expandable cards must expose a chevron."
Assert-Contains $dashboard "activityDetailRow" "Activity panel expanded details must use structured label/value rows."
Assert-Contains $dashboard "function activityGroupForCard" "Activity panel accordion must be scoped by logical group."
Assert-Contains $dashboard "--activity-card-compact-min-height" "Activity simple compact cards must use a shared compact height token."
Assert-Contains $dashboard "--activity-card-summary-min-height" "Activity cards with a secondary summary must use a separate density token."
Assert-Contains $dashboard "--activity-value-min-height" "Activity compact cards must reserve a consistent value row."
Assert-Contains $dashboard "activity-has-summary" "Activity cards must toggle a structural summary density class."
Assert-Contains $dashboard "align-items:stretch!important" "Activity compact grid rows must stretch closed cards to the same height."
Assert-Contains $dashboard "-webkit-line-clamp:2" "Activity compact card values and summaries must clamp to two lines."
Assert-Contains $dashboard ".activityPanel .focusLine.activity-expandable.expanded" "Activity expanded cards must have a dedicated full-width rule."
Assert-Contains $dashboard "height:auto!important" "Activity expanded cards must return to natural height."
Assert-Contains $dashboard "function formatUdpTelemetryInline" "Zero Ping compact card must separate module state from monitored-process summary."
Assert-Contains $dashboard "function formatShaderBoostInline" "ShaderBoost compact card must separate module state from readiness summary."
Assert-Contains $dashboard "function formatCpuBoundAssistInline" "CPU-Bound Assist compact card must use specific operational summaries when present."
Assert-Contains $dashboard "function formatStreamTelemetryInline" "Live Guard compact card must use specific operational summaries when present."
Assert-Contains $dashboard "function hasActivityGameContext" "CPU-Bound Assist must be rendered only from real game/backend context."
Assert-Contains $dashboard "function hasActivityLiveContext" "Live Guard must be rendered only from live/mode/backend context."
Assert-Contains $dashboard "function updateActivityResourceVisibility" "Activity resources must be contextually hidden and reflowed."
Assert-Contains $dashboard "function setActivityCardVisible" "Activity resource cards must not rely on CSS-only hiding."
Assert-Contains $dashboard "activity-span-full" "Odd active resource cards must span the full row instead of leaving holes."
Assert-Contains $dashboard ".activityPanel .activityGroupLabel[hidden]" "Active resources label must be hidden when no relevant resources remain."
Assert-Contains $dashboard "function formatMemoryHeadline" "Activity panel memory card must handle 0 MB without looking like a failure."
Assert-Contains $dashboard "function formatPassInsight" "Activity panel latest pass card must summarize the whole pass consistently."
Assert-Contains $dashboard "function formatPassActivityDetails" "Activity panel latest pass expanded details are missing."
Assert-Contains $dashboard "function formatPressureActivityDetails" "Activity panel pressure expanded details are missing."
Assert-Contains $dashboard "function formatGpuPressureActivityDetails" "Activity panel GPU expanded details are missing."
Assert-Contains $dashboard "function formatShaderBoostActivityDetails" "Activity panel ShaderBoost expanded details are missing."
Assert-Contains $dashboard 'txt("engineTop",formatTopImpact(s))' "Activity panel top impact must use the resilient formatter."
Assert-NotContains $dashboard 'class="focusLine metric-pressure"' "Activity panel must not render latest relief as an orphan metric card."
Assert-NotContains $dashboard 'memoryEffectInsightK:"Efeito de memória"' "Activity panel must not duplicate reclaimed memory as memory effect."
Assert-Contains $dashboard 'latestDecisionInsightK:"Último passe"' "Activity panel must rename latest adjustment into latest pass when summarizing multiple actions."
Assert-NotContains $dashboard 'latestDecisionInsightK:"Último ajuste"' "Activity panel must not call a pass summary the latest adjustment."
Assert-NotContains $dashboard 'Stack preservada: sem DNS/IP/Winsock/driver' "Zero Ping detail copy must not expose raw stack-preservation text."
Assert-NotContains $dashboard 'Coleta: ' "GPU detail copy must not expose raw collection wording."
Assert-Contains $dashboard 'cardPassActionsK:"Última intervenção"' "Quick cards must rename pass actions into a unique intervention insight."
Assert-Contains $dashboard 'cardUdpK:"Última detecção UDP"' "Quick cards must not duplicate the Zero Ping module title."
Assert-Contains $dashboard 'cardShaderK:"Saúde do cache gráfico"' "Quick cards must not duplicate the ShaderBoost telemetry title."
Assert-NotContains $dashboard 'cardPassActionsK:"Ações no passe"' "Quick cards must not mirror applied actions."
Assert-NotContains $dashboard 'cardUdpK:"Zero Ping"' "Quick cards must not mirror the Zero Ping module title."
Assert-NotContains $dashboard 'cardShaderK:"ShaderBoost"' "Quick cards must not mirror the ShaderBoost telemetry title."
Assert-Contains $dashboard 'backdrop-filter:none!important' "Large glass surfaces must disable expensive backdrop filters in the performance recovery layer."
Assert-Contains $dashboard "v0.7.0 premium motion system" "Premium motion system layer is missing."
Assert-Contains $dashboard "--motion-standard" "Global motion duration tokens are missing."
Assert-Contains $dashboard "--ease-enter" "Global motion easing tokens are missing."
Assert-Contains $dashboard "function updateMotionPolicy" "Motion performance policy helper is missing."
Assert-Contains $dashboard "motion-gameplay" "Gameplay motion reduction state is missing."
Assert-Contains $dashboard "motion-minimized" "Minimized-window motion reduction state is missing."
Assert-Contains $dashboard "motion-pending" "Command pending feedback is missing."
Assert-Contains $dashboard "acknowledgeMotionCommands" "Command feedback must be acknowledged by engine state."
Assert-Contains $dashboard "motion-value-change" "Metric change feedback is missing."
Assert-Contains $dashboard "toastHost" "Toast host is missing."
Assert-Contains $dashboard "prefers-reduced-motion:reduce" "Reduced motion handling is missing."
Assert-Contains $dashboard "animation:motionButtonSpin .72s linear infinite" "Only command-bound pending spinner should be allowed for button loading feedback."
Assert-Contains $dashboard "v0.7.0 policy control alignment" "Policy control alignment repair is missing."
Assert-Contains $dashboard ".policyBtn:hover," "Policy buttons must override hover lift so the row stays aligned."
Assert-Contains $dashboard "v0.7.2 engine mode card polish" "Engine mode card polish layer is missing."
Assert-Contains $dashboard "v0.7.3 engine mode details de-duplication" "Engine mode details de-duplication layer is missing."
Assert-Contains $dashboard 'id="modeSelectedValue"' "Engine mode selected value is missing."
Assert-Contains $dashboard 'id="modeAppliedValue"' "Engine mode applied value is missing."
Assert-Contains $dashboard 'id="currentPowerPlanValue"' "Engine mode current power plan value is missing."
Assert-Contains $dashboard 'id="recommendedPowerPlanValue"' "Engine mode recommended power plan value is missing."
Assert-Contains $dashboard 'id="modeControlState"' "Engine mode control state is missing."
Assert-Contains $dashboard 'id="modeDetailTitle"' "Engine mode lower panel must use an explanatory details title."
Assert-Contains $dashboard 'id="modePriorityTags"' "Engine mode priority tags are missing."
Assert-Contains $dashboard 'class="modeFacts"' "Engine mode must keep the old lower-right status blocks."
Assert-Contains $dashboard 'class="modePlanNote"' "Engine mode selected summary must mention the associated plan without replacing the popup."
Assert-NotContains $dashboard 'id="selectedModeIcon"' "Engine mode lower panel must not duplicate the selected card icon."
Assert-NotContains $dashboard 'id="modeSelectionState"' "Engine mode lower panel must not duplicate the selected/applied badge."
Assert-Contains $dashboard 'data-i18n="modeGamingD"' "Engine mode cards must keep short descriptions."
Assert-Contains $dashboard 'data-i18n="modeGamingPill"' "Engine mode cards must keep semantic chips."
Assert-Contains $dashboard "openEnergyPrompt(normalized)" "Energy-sensitive modes must continue opening the confirmation popup."
Assert-Contains $dashboard "function modeRecommendedPlan" "Engine mode recommended-plan helper is missing."
Assert-Contains $dashboard "previewSessionMode" "Engine mode must show selected-but-pending state during energy confirmation."
Assert-Contains $dashboard "modeAppliedLabel" "Engine mode applied copy key is missing."
Assert-Contains $dashboard "modeSelectedLabel" "Engine mode selected copy key is missing."
Assert-Contains $dashboard "modePendingLabel" "Engine mode pending copy key is missing."
Assert-Contains $dashboard 'modeCompetitivePill = LANGS[k].modeCompetitivePill || "Response"' "Competitive mode chip fallback must use the standardized priority vocabulary."
Assert-Contains $dashboard 'modeCompetitivePill:"Resposta"' "Portuguese competitive mode chip must use response vocabulary."
Assert-Contains $dashboard 'modeWorkPill:"Responsivo"' "Portuguese work mode chip must use the refined vocabulary."
Assert-Contains $dashboard 'modeFocusPill:"Fundo leve"' "Portuguese focus mode chip must use the refined vocabulary."

Assert-Contains $launcher "ResponsiveMinWindowWidth = 560.0" "WebView host minimum width must allow restored narrow windows."
Assert-Contains $launcher "ResponsiveMinWindowHeight = 460.0" "WebView host minimum height must allow compact windows."
Assert-Contains $launcher "overlay.HorizontalAlignment = System.Windows.HorizontalAlignment.Stretch" "Drag overlay must stretch instead of using a fixed width."
Assert-Contains $launcher "WindowButtonReserveWidth" "Drag overlay must reserve window controls."
Assert-Contains $launcher "SetWindowDisplayAffinity" "Window capture affinity reset is missing."
Assert-Contains $launcher "AllowWindowCapture" "Window capture repair helper is missing."
Assert-NotContains $launcher "--disable-gpu" "WebView GPU must not be disabled; it causes low-FPS launcher rendering."
Assert-NotContains $launcher "--disable-gpu-compositing" "WebView compositor must not be disabled; capture repair must use window affinity instead."
Assert-Contains $launcher "GetRecommendedPowerPlanForSessionMode" "Backend must expose the recommended power plan instead of the launcher guessing it."
Assert-Contains $launcher "RecommendedPowerPlanName" "Dashboard state must include recommended power plan name."
Assert-Contains $launcher "GamePowerPlanName" "Dashboard state must include the game-mode power plan."
Assert-Contains $launcher "LivePowerPlanName" "Dashboard state must include the live-mode power plan."
Assert-Contains $launcher "ManualPolicyCount" "Dashboard state must expose the real manual policy count."

Assert-Contains $manifest "PerMonitorV2, PerMonitor" "Manifest must request PerMonitorV2 DPI awareness."

$responsiveBlock = [regex]::Match($dashboard, '/\* v0\.7\.0 responsive architecture[\s\S]*?</style>')
if (-not $responsiveBlock.Success) { throw "Could not isolate responsive architecture block." }
$block = $responsiveBlock.Value
Assert-Matches $block '@media\(max-width:900px\),\(max-aspect-ratio:4/5\)' "Portrait/narrow table-card breakpoint is missing."
Assert-Matches $block '@media\(max-height:760px\)' "Short-window modal handling is missing."
Assert-Matches $block '@media\(min-resolution:1\.5dppx\)' "DPI guard rules are missing."

"launcher responsive guard ok"


